### ISSUE TITLE
next step hyperlink formatting

### ISSUE THREAD

**Issue by jahoni** [phonegap/phonegap-docs#100]
![image](https://cloud.githubusercontent.com/assets/178345/7641201/74abdeec-fa88-11e4-8b53-453ebd08b462.png)

Minor, but the underline is SO FAT. anyway we can make it thinner, like the weight of the text?

**Comment by mwbrooks** [comment]
I'll assign this issue to @GarthDB. The underline is applied as a text decoration. We cannot use the `border-bottom` trick in this situation. Also, adjusting the `font-weight` has no impact on the underline weight.

**Comment by GarthDB** [comment]
@mwbrooks is right, I'll have to rework the way it's done, which is fine.
