### ISSUE TITLE
footer link: plugin library

### ISSUE THREAD

**Issue by jahoni** [phonegap/phonegap-docs#101]
currently, the footer link to "Plugin Library" (under the "Docs & Resources" section") goes to https://build.phonegap.com/plugins. I think it should be pointing to http://plugins.cordova.io

**Comment by mwbrooks** [comment]
Agreed and nice catch! Updated.

**Comment by jahoni** [comment]
Looks like this change was reverted

**Comment by mwbrooks** [comment]
Yep, it looks like @hollyschinsky's merge (4144e8d6d645853963d8d9790ad798cc478a9c7a) reverted it.

I've cherry-picked my commit again.
