### ISSUE TITLE
Add "Edit in Github" link to each article

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/phonegap-docs#102]
Each article should link back to the Github article's edit page, so that people can easily make changes.

**Comment by GarthDB** [comment]
If the user doesn't have commit rights we can't really send them to an edit page, but we can them to where the page is in the github repo and they would have to fork it to edit it.

**Comment by GarthDB** [comment]
Changed the label to "Edit this page in GitHub"; it seems a bit more clear.

**Comment by mwbrooks** [comment]
Nice Garth!
