### ISSUE TITLE
header/logo formatting

### ISSUE THREAD

**Issue by jahoni** [phonegap/phonegap-docs#103]
I'd like to tighten up the existing header height, and reduce the size of the PhoneGap symbol (not just the as wordmark, which is what the current implementation is showing)

Current implementation: (header height = 100px)

![image](https://cloud.githubusercontent.com/assets/178345/7641425/f0cbd62a-fa89-11e4-81ac-f59b2fa581f8.png)

Intended design (from mock-up): (header height = 72px)

![image](https://cloud.githubusercontent.com/assets/178345/7641404/d6514ca8-fa89-11e4-8ace-271d7922743e.png)

**Comment by jahoni** [comment]
The current implementation has the symbol and wordmark as two separate elements (symbol is SVG, wordmark is text)...maybe we ought to make the whole thing an image?

i've just created an SVG if this is the best approach...found here: https://www.dropbox.com/s/ebucndh0jsm51d9/logo.svg?dl=0

**Comment by mwbrooks** [comment]
@GarthDB I've assigned this to you. If you aren't available to work on it in the next few days, just me a ping and I'll take a stab at it. From poking around, I'm afraid that my _updates_ will need your review anyways.

**Comment by GarthDB** [comment]
for now it was a bit easier to just adjust the size and tighten the margin.

Here's an onion skin of what it looks like now compared with the design file.
![image](https://cloud.githubusercontent.com/assets/125516/7663293/606585ce-fb68-11e4-9ef0-d27e435842a6.png)

The mark is fine, but the tracking is a bit different on the web.
