### ISSUE TITLE
Secondary Nav: Current page indication

### ISSUE THREAD

**Issue by jahoni** [phonegap/phonegap-docs#104]
Would be great if we could get the current page highlighted in the secondary navigation.

Currently:

![image](https://cloud.githubusercontent.com/assets/178345/7651421/8a52721a-fb00-11e4-9737-0a08392456c3.png)

Mock-up: (hex colour #ee3551)

![image](https://cloud.githubusercontent.com/assets/178345/7651435/b564c250-fb00-11e4-8abc-74d546d519d2.png)

**Comment by jahoni** [comment]
Maybe this is related to/covered by #52 ?

**Comment by GarthDB** [comment]
@jahoni it will definitely be in the dynamically collapsing nav, but let me see what I can rig in our static stopgap.
