### ISSUE TITLE
Step 1: Install PhoneGap page - slight editing?

### ISSUE THREAD

**Issue by VinuL** [phonegap/phonegap-docs#111]
On this link:

http://docs.phonegap.com/getting-started/1-install-phonegap/desktop/

where it says

"Select your operating system to continue:â€¨â€¨"

You can see some funny characters after "continue:"

I have used Firefox, Safari and Chrome on Windows 7 desktop - and all display funny characters after the colon.

It is not a bug - just a slight re-edit perhaps?

Thank you.

![screenshot](https://cloud.githubusercontent.com/assets/11032258/7889173/c4974cc6-0635-11e5-80e0-a5c00c9e750d.png)

**Comment by GarthDB** [comment]
Thanks. I'll take care of it.

**Comment by GarthDB** [comment]
I fixed it and it should be deploying shortly.  I'll reopen if there is still an issue after deployment.

**Comment by VinuL** [comment]
Excellent. I see it sorted. Thanks.
