### ISSUE TITLE
Rewording perhaps?

### ISSUE THREAD

**Issue by VinuL** [phonegap/phonegap-docs#112]
On this link

http://docs.phonegap.com/develop/hello-world-explained/

Where it says 

"Including this file reference ensures the Cordova APIs to access those features are all available."

Could it perhaps be....

"Including this file reference ensures the Cordova APIs have access to those features and are all available."

or

"Including this file reference ensures the Cordova APIs have access to those features and are available."

or 

"Including this file reference enables the Cordova APIs to access to those features and makes sure they are available."

Not sure.....perhaps it is right and am not reading it right? Not sure. 

Thank you.

![screenshot2](https://cloud.githubusercontent.com/assets/11032258/7891285/750dc7f8-0643-11e5-93c7-4d3fbb6e9089.png)

**Comment by GarthDB** [comment]
Thanks @VinuL. Fixed.

I really appreciate you filling the issues. Feel free to make pull requests in the future. If you need any help with making a pr feel free to ping me.

**Comment by VinuL** [comment]
Thank you Garth. I see it updated. Brilliant. 

Will try make a pull request next time.
