### ISSUE TITLE
Create Article for Embedding Webview on Android

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/phonegap-docs#116]
This article can go through multiple editions. The first edition can assume that there is no assistant and explain how to embed an Apache Cordova webview into an existing Android app. This may or may not include how to use plugins.

In time, we can simply the process of embedding the webview and update the documentation.

**Comment by hollyschinsky** [comment]
The new guide is now available [here](http://docs.phonegap.com/develop/1-embed-webview/android/). 

It also includes:
1. A [sample app](https://github.com/phonegap/phonegap-sample-hybrid-android) for reference 
2. A new [hybrid bridge plugin](https://github.com/hollyschinsky/HybridBridgePlugin)
