### ISSUE TITLE
Content width is too narrow 

### ISSUE THREAD

**Issue by hollyschinsky** [phonegap/phonegap-docs#121]
It would be nice if we could have less margin and more usable space for content and code snippets to display. 

<img width="1550" alt="screen shot 2015-07-17 at 1 42 03 pm" src="https://cloud.githubusercontent.com/assets/359935/8753385/68c58172-2c89-11e5-9cb0-c537cb1cf70c.png">

**Comment by GarthDB** [comment]
I expanded the width with the latest implementation of the global style sheet from http://github.com/phonegap/phonegap.github.io
