### ISSUE TITLE
Implement 'click to expand' in sidebar

### ISSUE THREAD

**Issue by hollyschinsky** [phonegap/phonegap-docs#122]
Allow sidebar menu items to click to expand into subsection links to make things easier to find and read.

For example:
<img width="1435" alt="expanded-menu" src="https://cloud.githubusercontent.com/assets/359935/8811546/a5a05d86-2fc4-11e5-814a-99953d2a19b3.png">

**Comment by wildabeast** [comment]
One thing I found with the existing menu was when I was in the PGB context, the PGB menu was down off my screen and I would have to scroll my whole page to access my current menu state. Would be nice if current menu context was visible at left.

Likely fixed inherently by your redesign but better than bringing it up after you've redesigned :beer:

**Comment by hollyschinsky** [comment]
Thanks for the feedback Ryan ~ Joni, Garth and I will actually be discussing docs nav today!

**Comment by GarthDB** [comment]
@hollyschinsky this isn't happening anymore because we are using landing pages right? it isn't expanding with javascript?

**Comment by hollyschinsky** [comment]
@GarthDB No this will no longer be an issue once staging is finalized and pushed.
