### ISSUE TITLE
Add Error Page

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/phonegap-docs#127]
We could use a 404 error page, when a page does not exist.

At the moment, it displays the `index.html`, which can be misleading.

**Comment by GarthDB** [comment]
I have the error page setup, but we need to fix the redirect that's happening right now to back to the mainpage. How is the site being served? It is being built statically, but what is serving it and how does it handle custom 404 pages? @mwbrooks ?

**Comment by GarthDB** [comment]
Works! Thanks @mwbrooks

**Comment by mwbrooks** [comment]
:+1: 
![screen shot 2016-02-29 at 10 46 29 am](https://cloud.githubusercontent.com/assets/21328/13405102/b9d44a3a-ded1-11e5-9e5a-8979b23673a4.png)
