### ISSUE TITLE
Add Microdata to Docs

### ISSUE THREAD

**Issue by GarthDB** [phonegap/phonegap-docs#128]
![image](https://cloud.githubusercontent.com/assets/125516/9639895/a3c188d2-516b-11e5-9f3b-eb0cef53c408.png)

Right now Google is creating a result summary for the docs site and we have the ability to [annotate our content](https://developers.google.com/structured-data/) using [Microdata](http://schema.org/).

**Comment by mwbrooks** [comment]
@GarthDB is this related to the site map work?

**Comment by GarthDB** [comment]
Not exactly. They both help google indexing.

**Comment by GarthDB** [comment]
Issue moved to [phonegap/phonegap.github.io #177](https://github.com/phonegap/phonegap.github.io/issues/177) via [**ZenHub**](https://www.zenhub.com/)
