### ISSUE TITLE
Highlight Navigation when Expanded / Collapsed

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/phonegap-docs#129]
I noticed that the first pass at the expand / collapse navigation menu has been added. Awesome!

When a navigation section has been selected, it is highlighted in red. For example, navigating to _Plugin APIs_.

<img width="507" alt="screen shot 2015-09-10 at 10 39 16 am" src="https://cloud.githubusercontent.com/assets/21328/9795936/40478d18-57a8-11e5-9d81-5b94adfa3634.png">

However, when the expand / collapse section is initially selected, the top-level item is not highlighted. For example, clicking _PhoneGap CLI_ should highlight _PhoneGap CLI_ in red, but it doesn't:

<img width="679" alt="screen shot 2015-09-10 at 10 40 38 am" src="https://cloud.githubusercontent.com/assets/21328/9795960/694993aa-57a8-11e5-837b-3b460f522c9e.png">

Once you navigation to a sub-section, then it highlights in red correctly. For example, _Installing the CLI_:

<img width="996" alt="screen shot 2015-09-10 at 10 41 15 am" src="https://cloud.githubusercontent.com/assets/21328/9795974/80b604a6-57a8-11e5-81a1-bba65630fb32.png">

**Comment by hollyschinsky** [comment]
Good catch - this is a bug currently in the docs as well since that main item is a page itself and should be highlighted if selected regardless of expand/collapse state.

**Comment by hollyschinsky** [comment]
Fixed and merged.
