### ISSUE TITLE
Embedding the Webview for Android doesn't really embed the Webview

### ISSUE THREAD

**Issue by jcesarmobile** [phonegap/phonegap-docs#146]
I've been reading the docs about embedding the Webview, and the Android tutorial doesn't really embed the Webview (http://docs.phonegap.com/develop/1-embed-webview/android/)
It just creates a cordova-android project, add some plugins and launch an intent that show a native view when you click a button.
That's not embedding a webview, that can be done on a regular cordova project with a plugin that launches an intent.

I think this doc should tell how to really integrate a cordova webview inside a native project, mixing the cordova webview with other native elements on the same screen as the old docs did.

**Comment by hollyschinsky** [comment]
@jcesarmobile - Hey there, yes, you're absolutely right in that the approach documented is not addressing the way most would typically go about this. There's work in progress to help make this whole process more automated, but in the meantime we could add the [session/samples Anis and Eddy did for PhoneGap Day to use for some docs if that could help.
