### ISSUE TITLE
Database: undocumented changeVersion signature

### ISSUE THREAD

**Issue by realtebo** [phonegap/phonegap-docs#15]
http://docs.phonegap.com/en/edge/cordova_storage_storage.md.html#Database

1 - The changeVersion is almost NOT documented and explained in day-by-day usage
2 - the changeVersion has a differente signature call  like this

db.changeVersion(oldversion, newversion, alterfunc, errorfunc, successfunc)

I learn from this blog post [http://www.raymondcamden.com/index.cfm/2013/8/14/Updating-PhoneGap-Databases] that apple website is more well documented about this method

See http://developer.apple.com/library/safari/documentation/iphone/conceptual/safarijsdatabaseguide/UsingtheJavascriptDatabase/UsingtheJavascriptDatabase.html#//apple_ref/doc/uid/TP40007256-CH3-XSW1

Quality of your doc is growing every day, please keep it growing, and update this one !
Thanks for all of your work

**Comment by mwbrooks** [comment]
Closing this issue because the documentation is going through a major overhaul.
