### ISSUE TITLE
Read our blog link in footer

### ISSUE THREAD

**Issue by jahoni** [phonegap/phonegap-docs#150]
![ssp_temp_capture](https://cloud.githubusercontent.com/assets/178345/13155400/5c9f2a76-d632-11e5-97c7-e2635842f94d.png)

some weirdo characters in there there, and currently goes to http://docs.phonegap.com/blog but _should_ direct to http://www.phonegap.com/blog

**Comment by jahoni** [comment]
Any chance that this and issue #143 can be fixed up prior to the launch of the new .com on Feb 19?

**Comment by cfjedimaster** [comment]
New site coming? :)
