### ISSUE TITLE
Anchored titles are hidden by header

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/phonegap-docs#152]
**Example**

1. Click: http://docs.phonegap.com/getting-started/1-install-phonegap/desktop/#win
2. You'll notice that the title _Windows_ is hidden.
3. Scroll up
4. Ah, there it is!

<img width="1159" alt="screen shot 2016-02-23 at 3 37 00 pm" src="https://cloud.githubusercontent.com/assets/21328/13270504/747722e2-da43-11e5-989b-1493d1367948.png">

**Comment by GarthDB** [comment]
Related to https://github.com/phonegap/phonegap.github.io/issues/98
