### ISSUE TITLE
"Step 4: Run Your App" should be "Step 4: Preview Your App"

### ISSUE THREAD

**Issue by jcesarmobile** [phonegap/phonegap-docs#153]
As the first paragrah says "You can use the PhoneGap Developer App paired with PhoneGap Desktop to **immediately preview your app** on a device without installing platform SDKs, registering devices, or compiling code."

The title should make clear that they are not running the app, they are just previewing it. And the doc should tell that some things might not work the same way they work when you actually run it, and that they can't use 3rd party plugins while previewing the app.

**Comment by GarthDB** [comment]
What wording would accomplish this well?

**Comment by cfjedimaster** [comment]
I think there are two issues here, and it should possibly be split up. The title change as described seems perfect to me. 

As for the second part - maybe add a section at the end (after "Making Updates") called "A Note about This Approach". Then write a paragraph that explains how the dev app is loading your code via the network and that you can only use the 'core' list of plugins (you can list them out quickly) and that code that makes use of file based URIs will not work. A prime example of this is the Camera plugin. If you use the file uri option, which is documented as the preferred method, then it will not work.

If this seems kinda ok to folks, I'll take a stab at writing something.

**Comment by jcesarmobile** [comment]
Or maybe at the beginning as people, once they got it working, usually don't keep scrolling to the end. Or at least comment at the beginning that using the preview approach have some problems and add a link to the "A Note about This Approach"

**Comment by cfjedimaster** [comment]
I'd worry about it being in the beginning, but I think it would be ok to have a very short note like, "(Please see important notes about the Developer app at the end of this article.)".

**Comment by mwbrooks** [comment]
Thanks @jcesarmobile and @cfjedimaster,

I agree, this issue can track changing the title from _Run Your App_ to _Preview Your App_. It's a great suggestion that uses the terminology that we are trying to keep consistent.

I've created issue #155 to track documenting the limitations of the PhoneGap Developer App. I want this to be a separate reference article rather than mixing it into another section. Both the _Previewing your App_ and _Making Update_ should reference this section.

**Comment by mwbrooks** [comment]
The above commit is now deployed:
http://docs.phonegap.com/getting-started/4-preview-your-app/desktop/

**Comment by jcesarmobile** [comment]
On Get started page, the point 4 is still "Run your app" http://phonegap.com/getstarted/
