### ISSUE TITLE
Broken link. http://phonegap.com/install/ shows 404 screen

### ISSUE THREAD

**Issue by jcesarmobile** [phonegap/phonegap-docs#160]
On http://app.phonegap.com/, the "First, install the desktop app" section, there is a link to http://phonegap.com/install/

I think it should point to

http://docs.phonegap.com/getting-started/1-install-phonegap/desktop/

**Comment by GarthDB** [comment]
@jcesarmobile http://app.phonegap.com has been replaced by http://phonegap.com/products/
I just set up a redirect; thanks.
