### ISSUE TITLE
On Get started page, the point 4 is still "Run your app" 

### ISSUE THREAD

**Issue by jcesarmobile** [phonegap/phonegap-docs#164]
I opened https://github.com/phonegap/phonegap-docs/issues/153 where I said that "Step 4: Run Your App" should be "Step 4: Preview Your App"

It was fixed on the docs section, but the Get started page (http://phonegap.com/getstarted/) still shows "Run your new app on your device". 

I think it should be changed there too.

**Comment by jcesarmobile** [comment]
It says preview now, closing...

But I still see a lot of people confused because 3rd party plugins don't work on the developer app.

**Comment by GarthDB** [comment]
Agreed. I'm going to stub out the more complete docs that would help clear this up.
