### ISSUE TITLE
Page content heading styling

### ISSUE THREAD

**Issue by jahoni** [phonegap/phonegap-docs#182]
Right now, there is inconsistent usage of heading styles on docs pages. The rule to follow is this:

Every page should begin with H2, and then go from there.

**Comment by jahoni** [comment]
I wonder - does it actually make more sense to change the H1 styling, @GarthDB ?

**Comment by GarthDB** [comment]
If say semantics first. So the page title should be an h1 (which is generated by the template from the title property) so the docs content should start with h2.

**Comment by jahoni** [comment]
Alright
