### ISSUE TITLE
New Landing Page Layout: Getting Started Guide

### ISSUE THREAD

**Issue by jahoni** [phonegap/phonegap-docs#187]
Slightly revised content, and an updated layout in the mock-up ([PSD](https://www.dropbox.com/s/o1divx679fwocm6/docs-mockup.psd?dl=0) - Layer Comp "Getting Started Landing").

I have introduced a new style here, for what I'd call "page content navigation"...the links to sub-sections within docs categories. This page, Getting Started, has a slightly specialized version of this style, with the inclusion of "STEP X" above (rather than in-line) the step/sub-category name.

![docs-desktop_0005_getting-started-landing](https://cloud.githubusercontent.com/assets/178345/15439767/b163f8a6-1e86-11e6-9040-5a152687ecfa.png)

**Comment by jahoni** [comment]
Also including on this issue, the approach to styling for page content navigation on handheld devices:

[PSD](https://www.dropbox.com/s/wriwnaao4i4gzr4/mockup-hand.psd?dl=0) - Layer Comp "docs-landing"

![docs-hand-landing](https://cloud.githubusercontent.com/assets/178345/15441027/67442258-1e8d-11e6-84a5-059273841e3c.png)

**Comment by jahoni** [comment]
Related to what is on staging:

- [ ] The first paragraph beneath the page title should be styled with slightly larger than body, grey text (mimicking what is found on the homepage). Currently, the styling on the docs homepage is inline as
style="color:#888888;font-size:1.35rem;line-height:1.9rem;"
- [ ] The first paragraph text should be edited to read: This guide is geared to helping people new to PhoneGap get up and running as quickly as possible with the least amount of setup and time.

**Comment by hollyschinsky** [comment]
Fixed the 1st paragraph and committed to staging per the 2nd bullet above.

**Comment by jahoni** [comment]
looks good on staging
