### ISSUE TITLE
New Landing Page Layout: PhoneGap Build

### ISSUE THREAD

**Issue by jahoni** [phonegap/phonegap-docs#190]
I've revised the layout of the PhoneGap Build docs landing page, and am suggesting that the overview content (currently displayed on the landing page on staging) be moved to a sub-section titled "Overview" - refer to #191 .

Otherwise, the mock-up ([PSD](https://www.dropbox.com/s/o1divx679fwocm6/docs-mockup.psd?dl=0) - Layer Comp "PhoneGap Build Landing") includes revised intro content and the page content navigation.

![docs-desktop_0008_phonegap-build-landing](https://cloud.githubusercontent.com/assets/178345/15440163/cd1d3f88-1e88-11e6-9c0a-0a3b6222c45f.png)

**Comment by jahoni** [comment]
Related to what is on staging:

- [ ] The first paragraph beneath the page title should be styled with slightly larger than body, grey text (mimicking what is found on the homepage). Currently, the styling on the docs homepage is inline as
style="color:#888888;font-size:1.35rem;line-height:1.9rem;"
- [ ] The first paragraph text should be edited to read: [PhoneGap Build](http://build.phonegap.com) is a cloud service for compiling PhoneGap applications. These docs will get you started, but if your question isn’t answered here you can always check out the [community forum](https://forums.adobe.com/community/phonegap/build).

**Comment by jahoni** [comment]
The first paragraph on staging includes the text "The first paragraph text should be edited to read" - that needs to be deleted.

Also in the first paragraph, funky characters being displayed in place of apostrophe in the word "isn't"

![ssp_temp_capture](https://cloud.githubusercontent.com/assets/178345/15719455/de1c7a32-27e4-11e6-982a-a3f0cb5375df.png)

The text below the content sub-menu ("Here are some of the benefits that PhoneGap Build provides:"....through to "...ensuring everyone is working on the most up-to-date version.") is contained on the "Overview" page, and should be deleted from the landing page.

![ssp_temp_capture](https://cloud.githubusercontent.com/assets/178345/15719565/5c6c0fe2-27e5-11e6-9b3b-43e6b56bb64a.png)

**Comment by jahoni** [comment]
The benefits text below the content sub-nav is still there. it needs to be deleted.

**Comment by GarthDB** [comment]
ah sorry I missed it. Fixing now.

**Comment by jahoni** [comment]
looks good on staging
