### ISSUE TITLE
Secured Server - PhoneGap desktop

### ISSUE THREAD

**Issue by Mandya-Naveen** [phonegap/phonegap-docs#192]
I am running PhoneGap Desktop v0.3.3, and would like to use getCurrentPosition() and watchPosition() api's. I cannot test them as getCurrentPosition() and watchPosition() are deprecated on insecure origins and its http server that is running on PhoneGap Desktop. Is there any way i can configure https server ? if not whats the alternate ( localhost is not an option)

**Comment by mwbrooks** [comment]
Hi @Mandya-Naveen,

Thanks for catching the insecure origin issue with Geolocation. I think there are two tasks within your issue:

1. We should look into supporting `https://localhost:3000`. 
2. You should [install the PhoneGap mobile app](http://docs.phonegap.com/getting-started/2-install-mobile-app/) and connect to the IP Address provided by the PhoneGap Desktop app.
  - This will allow you to preview the app on your phone and Geolocation will work correctly.

**Comment by Mandya-Naveen** [comment]
Hi Brooks,

   I tried with PhoneGap mobile app, it does not work there too. Thre also
we will be giving the IP address that is shown on Desktop App, and thats
http. So we have problem in that approach too.

Regards,
B. Naveen Kumar
9845928564

**Comment by mwbrooks** [comment]
Hi @Mandya-Naveen,

Hmm... the Mobile App should work. The Mobile App works by using the HTTP IP Address from the Destkop app to download a ZIP of your app, uncompress the ZIP, and then run the app on the `file://` protocol. This is identical to how a compiled Apache Cordova app works.

**Comment by GarthDB** [comment]
Not specifically a docs issue. If you'd like to continue the conversation @Mandya-Naveen I would recommend doing it on the [forums](https://forums.adobe.com/community/phonegap).
