### ISSUE TITLE
Active state on mobile menu broken 

### ISSUE THREAD

**Issue by hollyschinsky** [phonegap/phonegap-docs#193]
I noticed the active states in the mobile menu are no longer working correctly after the latest updates to staging. It should be highlighting the currently clicked item in red but it seems to either be showing too many in red or none at all. 

![screen shot 2016-05-31 at 6 15 23 pm](https://cloud.githubusercontent.com/assets/359935/15692245/605f3960-275b-11e6-96b2-cecd57aee3f4.png)
![screen shot 2016-05-31 at 6 15 57 pm](https://cloud.githubusercontent.com/assets/359935/15692246/606070a0-275b-11e6-9699-e4fec44ec408.png)

**Comment by jahoni** [comment]
Also refer to #183
