### ISSUE TITLE
Wikitude Augmented Reality Documentation

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/phonegap-docs#199]
**Description**

The PhoneGap Developer App now supports the Wikitude Augmented Reality plugin and we have an augmented reality template to show off a demo. It's now time to document how to use both and where to go from there.

**Reference**

- Branch: https://github.com/phonegap/phonegap-docs/tree/wikitude

**Comment by mwbrooks** [comment]
**Documentation Location**

Currently, the Augmented Reality documentation is added to the Developer App. Technically, this makes sense since the bulk of the implementation is in the Developer App.

![image](https://cloud.githubusercontent.com/assets/21328/15868797/3c774586-2c9e-11e6-847b-70a195c69401.png)

 However, conceptually it doesn't make sense to learn about PhoneGap's Augmented Reality demo by navigating to the Developer App. Instead, I think it makes more sense to include Augmented Reality under Tutorials, similar to the Push Notification tutorial:


![image](https://cloud.githubusercontent.com/assets/21328/15868946/ce2df09c-2c9e-11e6-802a-25e58c389b04.png)

**Comment by mwbrooks** [comment]
This is a great start @timkim with a good breakdown of the sections.

I think after the _Overview_ section, we will want two sections:

1. _Run from Hosted Template_
  - Explain connecting the Developer App to `http://ar.phonegap.com`
2. _Run from Local Template_
  - Explain using the `phonegap-template-ar` from the Desktop / CLI

Then leading into your other sections.

I also think we should consider calling it _wikitude_ instead of _ar_, so that we can support and encourage other augmented reality vendors.

**Comment by GarthDB** [comment]
👍 about the moving to the tutorials section.

**Comment by GarthDB** [comment]
It's been fixed.

![image](https://cloud.githubusercontent.com/assets/125516/16960462/ec10f4be-4da6-11e6-884f-3980503e52e3.png)
