### ISSUE TITLE
Items in language menu on docs not displaying properly

### ISSUE THREAD

**Issue by JaniceCampbell** [phonegap/phonegap-docs#223]
http://docs.phonegap.com/
The (machine translation) language menu is cutting off the bottom of the words. It might be a vertical centering issue or font is too large for graphical space. Please investigate. See screenshots. 
Chrome Version 53.0.2785.116 (64-bit) on Mac.
Not seeing the issue in FF 48.0.1 on Mac.
<img width="172" alt="screen shot 2016-09-21 at 11 21 36 am" src="https://cloud.githubusercontent.com/assets/22376518/18758112/9804e398-80ab-11e6-8016-5c2c80962b49.png">
<img width="208" alt="screen shot 2016-09-21 at 11 21 25 am" src="https://cloud.githubusercontent.com/assets/22376518/18758113/98092a66-80ab-11e6-9f38-e7a9891d59a7.png">

**Comment by GarthDB** [comment]
@JaniceCampbell what browser are you seeing that in?

**Comment by GarthDB** [comment]
@JaniceCampbell I fixed it, but it will take a few minutes to deploy.
![image](https://cloud.githubusercontent.com/assets/125516/18765993/4c830b5a-80d5-11e6-8432-5f5bbd98a310.png)
![image](https://cloud.githubusercontent.com/assets/125516/18766011/64575bc8-80d5-11e6-8986-39c66ce574c7.png)
