### ISSUE TITLE
Not able to add plugin using Plugman, getting below error.

### ISSUE THREAD

**Issue by rahulbm** [phonegap/phonegap-docs#225]
D:\Rahul Workspace\Phonegap Android Project\cordova-android-master\cordova-andro
id-master\bin\HybridAndroidApp>plugman install --platform android --project . --
plugin cordova-plugin-whitelist
Installing "cordova-plugin-whitelist" for android
ANDROID_HOME=D:\Rahul\ADT\adt-bundle-windows-x86_64-20140321\sdk
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_101\
Failed to install 'cordova-plugin-whitelist':CordovaError: Requirements check fa
iled for JDK 1.8 or greater at D:\Rahul Workspace\Phonegap Android Project\cordova-android-master\cordova-android-master\bin\HybridAndroidApp\cordova\lib\check_reqs.js:278:19
    at _fulfilled (D:\Rahul Workspace\Phonegap Android Project\cordova-android-m
aster\cordova-android-master\bin\HybridAndroidApp\cordova\node_modules\q\q.js:83
4:54)  at self.promiseDispatch.done (D:\Rahul Workspace\Phonegap Android Project\co
rdova-android-master\cordova-android-master\bin\HybridAndroidApp\cordova\node_mo
dules\q\q.js:863:30) at Promise.promise.promiseDispatch (D:\Rahul Workspace\Phonegap Android Project\cordova-android-master\cordova-android-master\bin\HybridAndroidApp\cordova\node_modules\q\q.js:796:13) at D:\Rahul Workspace\Phonegap Android Project\cordova-android-master\cordova-android-master\bin\HybridAndroidApp\cordova\node_modules\q\q.js:604:44 at runSingle (D:\Rahul Workspace\Phonegap Android Project\cordova-android-master\cordova-android-master\bin\HybridAndroidApp\cordova\node_modules\q\q.js:137:13)   at flush (D:\Rahul Workspace\Phonegap Android Project\cordova-android-master\cordova-android-master\bin\HybridAndroidApp\cordova\node_modules\q\q.js:125:13) at doNTCallback0 (node.js:407:9) at process._tickCallback (node.js:336:13)
Requirements check failed for JDK 1.8 or greater D:\Rahul Workspace\Phonegap Android Project\cordova-android-master\cordova-android-master\bin\HybridAndroidApp>cordova install --platform android --project . --plugin cordova-plugin-whitelist

**Comment by GarthDB** [comment]
@rahulbm is this a PhoneGap specific bug, or would it be better on https://github.com/apache/cordova-plugman ?

**Comment by rahulbm** [comment]
I am sure it is related to https://github.com/apache/cordova-android

**Comment by GarthDB** [comment]
@rahulbm I would recommend posting the issue there. This repo is meant for issues pertaining the the PhoneGap docs website. If you find a solution and believe it should be in these docs, feel free to make a pull request to add it.

**Comment by rahulbm** [comment]
OK @GarthDB, Thank you...
