### ISSUE TITLE
set up CI for phonegap-docs to run `npm run test` on PRs and/or master branch.

### ISSUE THREAD

**Issue by filmaj** [phonegap/phonegap-docs#236]
the README references that commits to master trigger deployment to docs.phonegap.com, so it sounds like some automation exists to a certain degree already.

would be good to hook in running the tests into this flow, and prevent auto-deploys that fail the tests. reporting the ci runs back to github via github webhooks would help make clear which PRs are safe to merge to boot.

**Comment by GarthDB** [comment]
DONE, thanks @filmaj for catching it.
