### ISSUE TITLE
Consistency, please...

### ISSUE THREAD

**Issue by andersborgabiro** [phonegap/phonegap-docs#262]
This is completely out of sync with what's described for Cordova at https://cordova.apache.org/docs/en/latest/config_ref/images.html and https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-splashscreen/index.html

Please fix this, as it confuses the hell out of developers that need to creates resources for both Cordova and PhoneGap (Build). After all, it's the same thing, and even more so with cli-7.0.1, so why make it different?

**Comment by purplecabbage** [comment]
I am assuming this was intended for https://github.com/apache/cordova-docs

**Comment by andersborgabiro** [comment]
It was the PhoneGap documentation that was out of sync with the one for Cordova so I referred to the correct information at Apache. The status might be better now.

**Comment by purplecabbage** [comment]
Noted, thanks.
We are working on getting rid of duplicate data, which should help with consistency.

**Comment by andersborgabiro** [comment]
That's great news. Thanks.
