### ISSUE TITLE
[stockpile-docs] More info on F7 this.$route, etc

### ISSUE THREAD

**Issue by devgeeks** [phonegap/phonegap-docs#274]
Perhaps we should have a bit more info on `this.$route` and its properties and methods the first time it gets introduced?

I think this is in `/tutorials/stockpile/5-results-part1/` in the section for the computed property for the `backLink`. 

> 1. In this new computed block, define a backLink property to determine which title to use on the link based on the route:

Maybe, a link to the F7-Vue Dynamic Route Matching docs? -- http://framework7.io/vue/navigation-router.html#dynamic-route-matching

**Comment by hollyschinsky** [comment]
I did actually have a green info block in the Renaming & Routing updates section in that same page where I link to that page and explain the dynamic routing a bit already but I will add some more notes about it on the `backLink` computed property too. It may not stand out enough.
