### ISSUE TITLE
Docs????

### ISSUE THREAD

**Issue by Bizarrus** [phonegap/phonegap-docs#310]
The Docs site from PhoneGap (http://docs.phonegap.com) gives me only a simple step-by-step guide for Noobs, but as an developer, i search for the JavaScript-API as an reasonable documentation.

I usually expect more than just some information on a documentation page. That makes Phonegap pretty unappealing.

How i can find the real documentation on the site from PhoneGap?

**Comment by chrisgriffith** [comment]
If you are looking for the interfaces between PhoneGap/Cordova and the native device, you might look here: https://cordova.apache.org/docs/en/latest/guide/hybrid/plugins/

However, many of the things you might consider doing may have already been done and you would just need to integrate the plugin into your app. I would review the Cordova plugin registry first.

**Comment by Bizarrus** [comment]
Thanks, but these are not listen on the PhoneGap site. That's annoying.
