### ISSUE TITLE
3.2.0 docs incomplete

### ISSUE THREAD

**Issue by jacobweber** [phonegap/phonegap-docs#35]
1. The index page (http://docs.phonegap.com/en/3.2.0/index.html) has a reference to "The Command Line Interface" but there's no link. On the other hand, the Overview page (http://docs.phonegap.com/en/3.2.0/guide_overview_index.md.html#Overview) does have a link to that page, and it works.

2. On "The Command Line Interface" (http://docs.phonegap.com/en/3.2.0/guide_cli_index.md.html#The%20Command-line%20Interface), there's no mention of how to add a platform to your project. So 

3. When I create an app, the www/config.xml file has entries like <icon> and <gap:splash>. But the "Icons and Splash Screens" page (http://docs.phonegap.com/en/3.2.0/config_ref_images.md.html#Icons%20and%20Splash%20Screens) makes no mention of these. Neither do the "Android Configuration" or "iOS Configuration" pages.

**Comment by mwbrooks** [comment]
Closing this issue because the documentation is going through a major overhaul.
