### ISSUE TITLE
Phonegap CLI doc missing replaced with cordova cli docs

### ISSUE THREAD

**Issue by csantanapr** [phonegap/phonegap-docs#39]
Phonegap CLI docs available on 3.2 but not available on latest 3.4

Talks about phonegap (i.e. phonegap local build)
http://docs.phonegap.com/en/3.2.0/guide_cli_index.md.html#The%20Command-Line%20Interface

Talks about cordova
http://docs.phonegap.com/en/3.4.0/guide_cli_index.md.html#The%20Command-Line%20Interface

We have some folks confuse that phonegap cli is not longer supported and people suggesting to uninstall phonegap and install cordova.
http://stackoverflow.com/questions/23190127/what-happen-to-phonegap-3-4-3-3-command-line-interface

**Comment by mwbrooks** [comment]
Closing this issue because the documentation is going through a major overhaul.
