### ISSUE TITLE
Add HTML Proofer Support

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/phonegap-docs#46]
Add HTML Proofer tests to the #44 rewrite branch.

If anyone knows of a node.js version of HTML Proofer, please let me know!

**Comment by afeld** [comment]
https://www.npmjs.com/package/broken-link-checker, maybe?

**Comment by GarthDB** [comment]
I've added [html-proofer](https://github.com/gjtorikian/html-proofer) to [PhoneGap Day](https://github.com/phonegap/phonegap-day); it would be pretty simple to duplicate it here.

**Comment by GarthDB** [comment]
I put this together and made a pull request.

https://github.com/phonegap/phonegap-docs/pull/172
