### ISSUE TITLE
Docs Styles Wish List

### ISSUE THREAD

**Issue by hollyschinsky** [phonegap/phonegap-docs#47]
1. Callouts (shaded text or otherwise marked) for notes, warnings and tips with a sidebar color / title or icon. 

   Reference ideas:
   - https://developer.mozilla.org/en-US/docs/Web/CSS/box-orient#Examples
   - http://getbootstrap.com/components/#glyphicons-examples
   - Joni’s original design mock-up for developer site

2. Panels for Examples - a titled boxed border with a space for a screenshot and example code 
     Reference ideas:
     - http://getbootstrap.com/components/#glyphicons-examples (*the box itself marked with EXAMPLE*)

3. Code highlighting by language except for terminal (see Joni’s original mock-up).

4. Button styles for Prev / Next (float left / right in a shape that looks like an arrow or otherwise)

5. Highlight the current section of the article in the sidebar navigation when scrolling thru content

**Comment by GarthDB** [comment]
Broke this apart into separate issues referenced above.
