### ISSUE TITLE
[minor] items that scroll in mobile, have a different background color when hidden area is revealed

### ISSUE THREAD

**Issue by shazron** [phonegap/phonegap-docs#56]
## Environment:
Mobile Safari 
iOS 8.2
iPhone 6 Plus

## Steps to repro:
1. Go to the  route "/guides/create" (in staging)
2. Find the first scrollable code snippet
3. Swipe it to the left to scroll the area

## Expected result:
The hidden scrollable area, when revealed, is the same color as the displayed scrollable area

## Actual result:
The hidden scrollable area, when revealed, is a different color from the displayed scrollable area

## Screenshot

![img_5729](https://cloud.githubusercontent.com/assets/36107/6971260/1848d624-d930-11e4-836d-2c58e888ccab.PNG)

**Comment by GarthDB** [comment]
Fixed with the code scrolling.
