### ISSUE TITLE
Unpublish content not included in first release

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/phonegap-docs#78]
## Problem

The current docs include a lot of great content. However, we do not plan to publish most of these articles on our first release. As the content is reviewed and polished, then we can release it.

We do not want to lose this content. We simply want to avoid including it in the production site.

## Articles to consider

- Tutorials/Configure Guides
- Tutorials/Develop Guides
- Tutorials/Optimize Guides
- Tutorials/Distribute Guides

## Solution

I see a few possible solutions:

1. Create a branch to backup the existing articles.
2. Move existing articles into a folder that is not rendered and published
3. Add a YAML Frontmatter option to flag drafts. `published: false` or `draft: true`.

**Comment by GarthDB** [comment]
We can add draft: true to the frontmatter.



—

**Comment by mwbrooks** [comment]
While we discussed adding a `draft` or `published` meta-data option. However, DocPad already supports a 'write' meta-data option that has the same functionality.

`write: false` will not write the article to the output path.

While it's not as descriptive as `draft` or `published` it does have documentation that is discoverable and allows us to solve this issue without adding more code complexity to the project.
