### ISSUE TITLE
Create homepage layout/content

### ISSUE THREAD

**Issue by jahoni** [phonegap/phonegap-docs#86]
Use the PSD located at: https://www.dropbox.com/s/4ul36qjkb1qinvb/docs-mockup-interimhome.psd?dl=0

with the robit svg at: https://www.dropbox.com/s/jqld4ypm0035wvm/excited_robit.svg?dl=0

**Comment by GarthDB** [comment]
I'm calling this good for now. It's not perfect, but it's a great placeholder until we get phonegap.com up.
