### ISSUE TITLE
Fix Content Formatting for "Installing PhoneGap CLI"

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/phonegap-docs#88]
## Problem

Browse to:
http://stage.docs.phonegap.com/getting-started/1-install-phonegap/cli/

The content is misaligned and overlapping the navigation.

![screen shot 2015-05-11 at 10 30 50 am](https://cloud.githubusercontent.com/assets/21328/7570911/d156dca4-f7c8-11e4-90a3-d9ca07c988c5.png)

**Comment by GarthDB** [comment]
I just pushed a fix for it.

**Comment by mwbrooks** [comment]
:smile:
