### ISSUE TITLE
Get rid of the FOUT

### ISSUE THREAD

**Issue by jahoni** [phonegap/phonegap-docs#90]
As you can see here: https://www.dropbox.com/s/8p3x3r8dhvgpp5j/typerenderflash.mov?dl=0
I see a significant flash of unstyled text on page load (http://blog.typekit.com/2010/10/29/font-events-controlling-the-fout/)

I'm not sure, but this article: http://blog.typekit.com/2013/08/21/best-practices-for-embedding-typekit/ may provide a solution.

**Comment by mwbrooks** [comment]
Thanks for submitting this issue. I was going to log it as well.

**Comment by GarthDB** [comment]
Fixed in the last push, it should deploy soon.
