### ISSUE TITLE
Question: Should this "Note" be a callout?

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/phonegap-docs#96]
At the start of the PhoneGap Desktop App Install guide:

![screen shot 2015-05-13 at 1 25 41 pm](https://cloud.githubusercontent.com/assets/21328/7620291/ae70a786-f973-11e4-9a61-288c65643f89.png)

**Comment by mwbrooks** [comment]
The same exists for the PhoneGap CLI Install guide.

**Comment by hollyschinsky** [comment]
Fixed
