### ISSUE TITLE
Footer: Most recent blog date

### ISSUE THREAD

**Issue by jahoni** [phonegap/phonegap-docs#98]
![image](https://cloud.githubusercontent.com/assets/178345/7641077/a89ab5c6-fa87-11e4-9865-4b431bd3751c.png)

Right now, the blog blurb is referencing March 24 as the most recent post date - the idea is that the date should auto update as new posts are published. For now, maybe we change the wording to:

Have you read our latest blog post yet? If not, go now…there is solid gold in that post.

**Comment by mwbrooks** [comment]
Good catch. I've updated it to your new suggestion!

**Comment by jahoni** [comment]
Looks like this change was reverted

**Comment by mwbrooks** [comment]
Hmm... Looks like @hollyschinsky merge (4144e8d6d645853963d8d9790ad798cc478a9c7a) reverted it.

I've cherry-picked my commit again.
